FROM python:alpine3.7
COPY . /app
COPY ./static /app/static
COPY ./templates /app/templates
COPY ./requirements.txt /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
CMD python ./index.py