version: '3.3'

services:
 web:
  build: .
  ports:
   - '5000:5000'
 db:
  image: mysql:5.7
  restart: always
  environment:
   MYSQL_DATABASE: 'dockerimage'
   MYSQL_USER: 'root'
   MYSQL_PASSWORD: 'P@$$w0rd'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - my-db:/var/lib/mysql

volumes:
  my-db: